alignoth/alignoth

- .github/workflows/rust.yml
This PR adds a code coverage report to the CI.
> ci: Add code coverage report

- README.md
This PR adds an installation guide and badges to the README.md
> docs: Update README.md with badges and installation

- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/main.rs
- src/plot.rs
This PR adds support for outputting tsv da with `--data-format` and therefore closes #10.
> feat: Support multiple output formats

- Cargo.lock
- src/cli.rs
- src/main.rs
This PR fixes a small offset of the highlighting area that occurred when using it.
> fix: Fix highlighting offset

- src/plot.rs
> fix: Improve error message when bam header doesn't contain given target

- Cargo.lock
- README.md
- src/cli.rs
- src/main.rs
- src/plot.rs
This PR closes #69 by implementing the `--around` parameter.
> feat: Add around parameter

- src/cli.rs
- src/main.rs
- src/utils.rs
This PR implements and closes #68.
> feat: Allow omitting reference and bam files if cwd only contains one of each

- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/main.rs
This PR implements and therefore closes #67.
> feat: Add option to plot full bam file

- README.md
- src/cli.rs
This PR implements and therefore closes #71.
> feat: Allow highlighting of single base position

- resources/plot.vl.json
- src/cli.rs
This PR fixes a off-by-one offset for reads and reference.
> fix: Fix offset of 1 base for reference and reads

- .github/workflows/rust.yml
See https://github.com/actions-rs/tarpaulin/issues/15 for more information.
> ci: Pin tarpaulin version

- resources/plot.vl.json
This PR closes #102 by showing the length of deletions via the tooltip.
> feat: Show length of deletions via tooltip

- resources/plot.vl.json
This PR fixes a duplicated legend that was introduced with #112.
> fix: Remove duplicated legend

- resources/plot.vl.json
This PR fixes a problem introduced in another recent fix that made insertions invisible.
> fix: Fix non-displayed insertions

- src/main.rs
- src/plot.rs
This PR adds a warning as the subtitle to the plot when reads are downsampled.
> feat: Show warning in plot when reads are downsampled

- resources/plot.vl.json
This PR adresses and closes #211 by showing the inserted bases for an insertion as a tooltip.
> feat: Show inserted bases in tooltip

- .github/workflows/release-please.yml
> ci: Change repository owner

- resources/plot.html.tera
This PR adds a small manual to HTML output explaining how use the plot.
> feat: Add manual for plot usage into HTML output

- resources/plot.html.tera
This PR adds an interactive read info table and some styling to plot page and should therefore close #103.
- Introduced a styled table to display read information dynamically.
- Added CSS for table and manual section for improved UI.
- Implemented click event to populate table with read details.
> feat: Add interactive read info table and styling to plot page

- resources/plot.html.tera
- resources/plot.vl.json
This pull request introduces enhancements to the `resources/plot.html.tera` and `resources/plot.vl.json` files, focusing on improving interactivity and user experience in the visualization. Key changes include adding multi-read selection functionality, implementing a tooltip for read flags, and introducing a utility function to decode read flags.
> feat: Enhanced multi-read selection with shift-click functionality
